version: 2.1

jobs:
  katalon-test:
    docker:
      - image: katalonstudio/katalon:latest
    steps:
      - checkout
      
      - run:
          name: Run Katalon Test
          command: |
            set -x
            set -o nounset

            echo "Preparing Test Parameters"
            PROJECT_PATH="$(pwd)/Katalon (v9 and v10) with BDD - Boilerplate.prj"
            TEST_SUITE_PATH="Test Suites/Web/TS - Login"
            BROWSER_TYPE="Chrome"
            EXECUTION_PROFILE="default"
            TEST_REPORT_PATH="$(pwd)/Reports"

            echo "Download and Extract KRE"
            wget -O Katalon_Studio_Engine_Linux.tar.gz https://download.katalon.com/10.0.0/Katalon_Studio_Engine_Linux_64-10.0.0.tar.gz
            tar -xzf Katalon_Studio_Engine_Linux.tar.gz
            ls -la

            echo "Upgrading environments"
            echo "Upgrade Google Chrome"
            chrome_package='google-chrome-stable_current_amd64.deb'
            wget -O $chrome_package  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dpkg -i $chrome_package || apt -y -f install
            
            echo "Wrap Chrome binary"
            WRAPPER_PATH=$(readlink -f /usr/bin/google-chrome)
            BASE_PATH="$WRAPPER_PATH-base"
            mv "$WRAPPER_PATH" "$BASE_PATH"
            
            cat > "$WRAPPER_PATH" \<<_EOF
            #!/bin/bash
            # Note: exec -a below is a bashism.
            exec -a "\$0" "$BASE_PATH" --no-sandbox "\$@"
            _EOF
            chmod +x "$WRAPPER_PATH"
            
            echo "$(google-chrome --version)" >> $KATALON_VERSION_FILE || true

            echo "Executing test"
            xvfb-run -s "-screen 0 $DISPLAY_CONFIGURATION" ./Katalon_Studio_Engine_Linux_64-10.0.0/katalonc -noSplash -runMode=console -retry=0 -projectPath="$PROJECT_PATH" -testSuitePath="$TEST_SUITE_PATH" -browserType="$BROWSER_TYPE" -executionProfile="$EXECUTION_PROFILE" -apiKey=$KATALON_API_KEY --config -webui.autoUpdateDrivers=true
            
            echo "Check latest directories"
            ls -la
            
            ret_code=$?
            exit $ret_code

      - store_artifacts:
          path: sample-bdd-project-in-katalon-latest-version/Reports/
          destination: Reports

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - katalon-test
