name: Run Katalon Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Katalon Runtime Engine
      - name: Download Katalon Runtime Engine
        run: |
          wget https://download.katalon.com/10.0.0/Katalon_Studio_Engine_Linux_64-10.0.0.tar.gz
          tar -xzf Katalon_Studio_Engine_Linux_64-10.0.0.tar.gz
          chmod -R 755 Katalon_Studio_Engine_Linux_64-10.0.0
      # Step 3: Set up Katalon license and environment variables
      - name: Set up environment
        env:
          KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }} # Tambahkan API Key di Secrets GitHub Actions
        run: |
          export PATH=$PATH:$(pwd)/Katalon_Studio_Engine_Linux_64-10.0.0

      # Step 4: Execute Katalon Test Suite
      - name: Run Katalon Test Suite
        run: |
          katalonc -noSplash -runMode=console -projectPath=$(pwd)/path/to/your_project.prj \
                   -testSuitePath=TestSuites/YourTestSuite \
                   -apiKey=$KATALON_API_KEY \
                   -reportFolder=Reports \
                   -reportFileName=report \
                   -retry=0 \
                   -browserType=Chrome
