name: Katalon Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action - Mobile Automation
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '9.6.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuitePath="Test Suites/Mobile/TS - Login" -browserType="Kobiton Device" -kobitonDeviceId=${{ secrets.KOBITON_DEVICE_ID }} -executionProfile="default" -testOpsProjectId=${{ secrets.TESTOPS_PROJECT_ID }} --config -kobiton.authentication.serverUrl="https://api.kobiton.com/wd/hub" -kobiton.authentication.username=${{ secrets.KOBITON_USERNAME }} -kobiton.authentication.apiKey=${{ secrets.KOBITON_API_KEY }} -webui.autoUpdateDrivers=true'
    - name: Upload Katalon Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: Katalon-Reports
          path: Reports/
