name: Katalon Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '9.7.3'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -runMode=console -retry=0 -testSuitePath="Test Suites/Test Suite - Login" -browserType="Chrome" -executionProfile="default" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
