name: Executing a Katalon Project on GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check API Key Length
      run: echo "API Key Length --> ${#KATALON_API_KEY}"
      shell: bash
      env:
        KATALON_API_KEY: ${{ secrets.KATALON_API_KEY }}
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
        version: '9.6.0'
        projectPath: '${{ github.workspace }}'
        args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Test Suite - Login" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
